### ISSUE TITLE
-roi option not working

### ISSUE THREAD

**Issue by khchuang** [rordenlab/niimath#26] opened 2024-07-19 02:49 UTC
I use niimath on MacOS Sonoma with M2 chip. The -roi option only generated an image with all 0. The original fslmaths works fine.

**Comment by neurolabusc** [comment] 2024-07-21 14:26
I am unable to replicate. I get identical results:

```bash
git clone git@github.com:rordenlab/niimath_tests.git
cd niimath_tests
fslmaths ./in/AIL -roi 5 19 3 22 2 28 0 1 fslout
niimath ./in/AIL -roi 5 19 3 22 2 28 0 1 niiout
niimath fslout --compare niiout
./conformance.sh
```
The final `conformance` script compares all possible orthogonal orientations (AIL AIR ALI ALS ARI ARS ASL ASR IAL IAR ILA ILP IPL IPR IRA IRP LAI LAS LIA LIP LPI LPS LSA LSP PIL PIR PLI PLS PRI PRS PSL PSR RAI RAS RIA RIP RPI RPS RSA RSP SAL SAR SLA SLP SPL SPR SRA SRP).

Please provide an example that illustrates the difference. If the dataset is large, you can share it with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by khchuang** [comment] 2024-08-01 06:00
Thanks for the test. Here is an example ROI mask with only two slices. I used the following the separate the part in slice 0:
niimath maskPCA -roi 0 -1 0 -1 0 1 0 -1 maskP1
The result is always 0....

[maskPCA.nii.gz](https://github.com/user-attachments/files/16450954/maskPCA.nii.gz)

**Comment by neurolabusc** [comment] 2024-08-05 00:48
OK, so the issue is that for ROI ` Inputting -1 for a size will set it to the full image extent for that dimension.` This is fixed with the latest commit and will be included in the next stable release. Please test and report if this resolves your issue.

**Closed as completed** 2024-08-17 18:41 UTC
